version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
